name: Build Plugin

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload plugin jar
      uses: actions/upload-artifact@v4
      with:
        name: plugin-jar
        path: target/*.jar
